require('dotenv').config();
module.exports={
    database:{
        host:process.env.HOST,
        database:process.env.DATA_BASE,
        user:process.env.USER,
        password:process.env.PASSWORD
    }
}